name: '[Workflow example] Code Review with AI'

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Run Octopulls
      uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
